# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gmesh.v1 import gmesh_pb2 as gmesh_dot_v1_dot_gmesh__pb2


class GMeshStub(object):
    """GMesh is the control-plane API exposed by the gmeshd daemon over a Unix
    socket. The GritivaCore agent, gmeshctl, and any other local process talks
    to gmeshd through this service.

    All mutating RPCs are idempotent on the {peer_id, mesh_ip} primary key.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/gmesh.v1.GMesh/Join',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.JoinRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.JoinResponse.FromString,
                )
        self.Leave = channel.unary_unary(
                '/gmesh.v1.GMesh/Leave',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.LeaveRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.LeaveResponse.FromString,
                )
        self.Status = channel.unary_unary(
                '/gmesh.v1.GMesh/Status',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.StatusRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.StatusResponse.FromString,
                )
        self.Version = channel.unary_unary(
                '/gmesh.v1.GMesh/Version',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.VersionRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.VersionResponse.FromString,
                )
        self.AddPeer = channel.unary_unary(
                '/gmesh.v1.GMesh/AddPeer',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.AddPeerRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.AddPeerResponse.FromString,
                )
        self.RemovePeer = channel.unary_unary(
                '/gmesh.v1.GMesh/RemovePeer',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.RemovePeerRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.RemovePeerResponse.FromString,
                )
        self.UpdatePeer = channel.unary_unary(
                '/gmesh.v1.GMesh/UpdatePeer',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.UpdatePeerRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.UpdatePeerResponse.FromString,
                )
        self.ListPeers = channel.unary_unary(
                '/gmesh.v1.GMesh/ListPeers',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListPeersRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListPeersResponse.FromString,
                )
        self.GetPeerStats = channel.unary_unary(
                '/gmesh.v1.GMesh/GetPeerStats',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.GetPeerStatsRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.GetPeerStatsResponse.FromString,
                )
        self.DiscoverNAT = channel.unary_unary(
                '/gmesh.v1.GMesh/DiscoverNAT',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.DiscoverNATRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DiscoverNATResponse.FromString,
                )
        self.HolePunch = channel.unary_unary(
                '/gmesh.v1.GMesh/HolePunch',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.HolePunchRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.HolePunchResponse.FromString,
                )
        self.SetupRelay = channel.unary_unary(
                '/gmesh.v1.GMesh/SetupRelay',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.SetupRelayRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.SetupRelayResponse.FromString,
                )
        self.AllocateWSTunnel = channel.unary_unary(
                '/gmesh.v1.GMesh/AllocateWSTunnel',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.AllocateWSTunnelRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.AllocateWSTunnelResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/gmesh.v1.GMesh/HealthCheck',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.HealthCheckResponse.FromString,
                )
        self.ScopeConnect = channel.unary_unary(
                '/gmesh.v1.GMesh/ScopeConnect',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ScopeConnectRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ScopeConnectResponse.FromString,
                )
        self.ScopeDisconnect = channel.unary_unary(
                '/gmesh.v1.GMesh/ScopeDisconnect',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ScopeDisconnectRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ScopeDisconnectResponse.FromString,
                )
        self.ApplyFirewall = channel.unary_unary(
                '/gmesh.v1.GMesh/ApplyFirewall',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ApplyFirewallRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ApplyFirewallResponse.FromString,
                )
        self.ResetFirewall = channel.unary_unary(
                '/gmesh.v1.GMesh/ResetFirewall',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ResetFirewallRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ResetFirewallResponse.FromString,
                )
        self.GetFirewallStatus = channel.unary_unary(
                '/gmesh.v1.GMesh/GetFirewallStatus',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.GetFirewallStatusRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.GetFirewallStatusResponse.FromString,
                )
        self.SubscribeEvents = channel.unary_stream(
                '/gmesh.v1.GMesh/SubscribeEvents',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.Event.FromString,
                )
        self.CreateEgressProfile = channel.unary_unary(
                '/gmesh.v1.GMesh/CreateEgressProfile',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.CreateEgressProfileRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.EgressProfileResponse.FromString,
                )
        self.UpdateEgressProfile = channel.unary_unary(
                '/gmesh.v1.GMesh/UpdateEgressProfile',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.UpdateEgressProfileRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.EgressProfileResponse.FromString,
                )
        self.DeleteEgressProfile = channel.unary_unary(
                '/gmesh.v1.GMesh/DeleteEgressProfile',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteEgressProfileRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteEgressProfileResponse.FromString,
                )
        self.ListEgressProfiles = channel.unary_unary(
                '/gmesh.v1.GMesh/ListEgressProfiles',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListEgressProfilesRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListEgressProfilesResponse.FromString,
                )
        self.EnableExit = channel.unary_unary(
                '/gmesh.v1.GMesh/EnableExit',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.EnableExitRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.EnableExitResponse.FromString,
                )
        self.DisableExit = channel.unary_unary(
                '/gmesh.v1.GMesh/DisableExit',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.DisableExitRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DisableExitResponse.FromString,
                )
        self.CreateIngressProfile = channel.unary_unary(
                '/gmesh.v1.GMesh/CreateIngressProfile',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.CreateIngressProfileRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.IngressProfileResponse.FromString,
                )
        self.UpdateIngressProfile = channel.unary_unary(
                '/gmesh.v1.GMesh/UpdateIngressProfile',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.UpdateIngressProfileRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.IngressProfileResponse.FromString,
                )
        self.DeleteIngressProfile = channel.unary_unary(
                '/gmesh.v1.GMesh/DeleteIngressProfile',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteIngressProfileRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteIngressProfileResponse.FromString,
                )
        self.ListIngressProfiles = channel.unary_unary(
                '/gmesh.v1.GMesh/ListIngressProfiles',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListIngressProfilesRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListIngressProfilesResponse.FromString,
                )
        self.CreateQuota = channel.unary_unary(
                '/gmesh.v1.GMesh/CreateQuota',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.CreateQuotaRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.QuotaResponse.FromString,
                )
        self.UpdateQuota = channel.unary_unary(
                '/gmesh.v1.GMesh/UpdateQuota',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.UpdateQuotaRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.QuotaResponse.FromString,
                )
        self.DeleteQuota = channel.unary_unary(
                '/gmesh.v1.GMesh/DeleteQuota',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteQuotaRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteQuotaResponse.FromString,
                )
        self.ListQuotas = channel.unary_unary(
                '/gmesh.v1.GMesh/ListQuotas',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListQuotasRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListQuotasResponse.FromString,
                )
        self.GetQuotaUsage = channel.unary_unary(
                '/gmesh.v1.GMesh/GetQuotaUsage',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.GetQuotaUsageRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.GetQuotaUsageResponse.FromString,
                )
        self.ResetQuota = channel.unary_unary(
                '/gmesh.v1.GMesh/ResetQuota',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ResetQuotaRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ResetQuotaResponse.FromString,
                )
        self.ListPathStates = channel.unary_unary(
                '/gmesh.v1.GMesh/ListPathStates',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListPathStatesRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListPathStatesResponse.FromString,
                )
        self.ListPolicies = channel.unary_unary(
                '/gmesh.v1.GMesh/ListPolicies',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListPoliciesResponse.FromString,
                )
        self.ReloadPolicies = channel.unary_unary(
                '/gmesh.v1.GMesh/ReloadPolicies',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ReloadPoliciesRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ReloadPoliciesResponse.FromString,
                )
        self.ListL7Flows = channel.unary_unary(
                '/gmesh.v1.GMesh/ListL7Flows',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListL7FlowsRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListL7FlowsResponse.FromString,
                )
        self.ListL7Totals = channel.unary_unary(
                '/gmesh.v1.GMesh/ListL7Totals',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListL7TotalsRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListL7TotalsResponse.FromString,
                )
        self.ListAnomalies = channel.unary_unary(
                '/gmesh.v1.GMesh/ListAnomalies',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListAnomaliesRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListAnomaliesResponse.FromString,
                )
        self.CreateCircuit = channel.unary_unary(
                '/gmesh.v1.GMesh/CreateCircuit',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.CreateCircuitRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.CircuitResponse.FromString,
                )
        self.UpdateCircuit = channel.unary_unary(
                '/gmesh.v1.GMesh/UpdateCircuit',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.UpdateCircuitRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.CircuitResponse.FromString,
                )
        self.DeleteCircuit = channel.unary_unary(
                '/gmesh.v1.GMesh/DeleteCircuit',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteCircuitRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteCircuitResponse.FromString,
                )
        self.ListCircuits = channel.unary_unary(
                '/gmesh.v1.GMesh/ListCircuits',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListCircuitsRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListCircuitsResponse.FromString,
                )
        self.InitCA = channel.unary_unary(
                '/gmesh.v1.GMesh/InitCA',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.InitCARequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.InitCAResponse.FromString,
                )
        self.CAStatus = channel.unary_unary(
                '/gmesh.v1.GMesh/CAStatus',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.CAStatusRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.CAStatusResponse.FromString,
                )
        self.IssueCert = channel.unary_unary(
                '/gmesh.v1.GMesh/IssueCert',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.IssueCertRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.IssueCertResponse.FromString,
                )
        self.ListCerts = channel.unary_unary(
                '/gmesh.v1.GMesh/ListCerts',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListCertsRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListCertsResponse.FromString,
                )
        self.RevokeCert = channel.unary_unary(
                '/gmesh.v1.GMesh/RevokeCert',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.RevokeCertRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.RevokeCertResponse.FromString,
                )
        self.ExportTrust = channel.unary_unary(
                '/gmesh.v1.GMesh/ExportTrust',
                request_serializer=gmesh_dot_v1_dot_gmesh__pb2.ExportTrustRequest.SerializeToString,
                response_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ExportTrustResponse.FromString,
                )


class GMeshServicer(object):
    """GMesh is the control-plane API exposed by the gmeshd daemon over a Unix
    socket. The GritivaCore agent, gmeshctl, and any other local process talks
    to gmeshd through this service.

    All mutating RPCs are idempotent on the {peer_id, mesh_ip} primary key.
    """

    def Join(self, request, context):
        """── Lifecycle ─────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Leave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPeer(self, request, context):
        """── Peers ─────────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverNAT(self, request, context):
        """── NAT & traversal ───────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HolePunch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupRelay(self, request, context):
        """── Relay / WS tunnel ─────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateWSTunnel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """── Health ────────────────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScopeConnect(self, request, context):
        """── Scopes (netns-isolated peers behind a VM) ─────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScopeDisconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyFirewall(self, request, context):
        """── Firewall (nftables) ───────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetFirewall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFirewallStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """── Event stream ──────────────────────────────────────────────────────
        Server-streaming RPC. Subscribers get async events: peer state changes,
        NAT re-discovery, health degradation, firewall apply results, etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEgressProfile(self, request, context):
        """── Egress profiles (Phase 11) ────────────────────────────────────────
        An egress profile routes selected outbound traffic through a specific
        mesh peer acting as an "exit node" instead of the local default gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEgressProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEgressProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEgressProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableExit(self, request, context):
        """Exit-side operations: called on the peer that acts as an exit node.
        EnableExit installs MASQUERADE + FORWARD rules so forwarded traffic
        egresses correctly; DisableExit tears them down.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableExit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIngressProfile(self, request, context):
        """── Ingress profiles (Phase 12) ───────────────────────────────────────
        Expose a backend service (running on another mesh peer, optionally
        inside a scope netns) on the edge peer's public address via nftables
        DNAT. Inbound packets are tunneled over the mesh to the backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIngressProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIngressProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIngressProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateQuota(self, request, context):
        """── Quotas (Phase 13) ────────────────────────────────────────────────
        Byte-counter-driven policy attached to an EgressProfile. Emits events
        when thresholds are crossed; optionally swaps traffic to a backup
        profile automatically at the shift threshold.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQuotas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuotaUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPathStates(self, request, context):
        """── Path Monitor (Phase 14) ──────────────────────────────────────────
        Reads the active path-probe state maintained by pathmon. The monitor
        auto-syncs targets from the peer registry every 30s; this RPC is a
        point-in-time snapshot of RTT, loss and up/down status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """── Policies (Phase 17) ──────────────────────────────────────────────
        List the active policies and force a reload from disk.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListL7Flows(self, request, context):
        """── L7 classifier (Phase 18) ─────────────────────────────────────────
        Per-protocol traffic visibility. Classification is port-based
        today — see docs/l7.md for the scope caveat (eBPF DPI is a
        follow-up).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListL7Totals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAnomalies(self, request, context):
        """── Anomaly alerts (Phase 21) ────────────────────────────────────────
        Recent alerts produced by the built-in detectors (bandwidth z-score,
        handshake storm, peer flap). Full live stream is available on the
        event bus as type `anomaly_alert`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCircuit(self, request, context):
        """── Circuits / onion paths (Phase 19) ────────────────────────────────
        A multi-hop source-routed path through the mesh. See docs/circuit.md
        for the role model (source/transit/exit) and security posture.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCircuit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCircuit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCircuits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitCA(self, request, context):
        """── mTLS / SPIFFE identity (Phase 20) ────────────────────────────────
        Small embedded CA: bootstrap once per mesh, issue short-lived peer
        certs with SPIFFE IDs, track revocations. The root cert can be
        handed to any peer that wants to terminate or validate TLS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CAStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueCert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeCert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportTrust(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GMeshServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.JoinRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.JoinResponse.SerializeToString,
            ),
            'Leave': grpc.unary_unary_rpc_method_handler(
                    servicer.Leave,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.LeaveRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.LeaveResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.StatusRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.StatusResponse.SerializeToString,
            ),
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.VersionRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.VersionResponse.SerializeToString,
            ),
            'AddPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPeer,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.AddPeerRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.AddPeerResponse.SerializeToString,
            ),
            'RemovePeer': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePeer,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.RemovePeerRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.RemovePeerResponse.SerializeToString,
            ),
            'UpdatePeer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePeer,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.UpdatePeerRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.UpdatePeerResponse.SerializeToString,
            ),
            'ListPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeers,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListPeersRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListPeersResponse.SerializeToString,
            ),
            'GetPeerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeerStats,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.GetPeerStatsRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.GetPeerStatsResponse.SerializeToString,
            ),
            'DiscoverNAT': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverNAT,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DiscoverNATRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.DiscoverNATResponse.SerializeToString,
            ),
            'HolePunch': grpc.unary_unary_rpc_method_handler(
                    servicer.HolePunch,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.HolePunchRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.HolePunchResponse.SerializeToString,
            ),
            'SetupRelay': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupRelay,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.SetupRelayRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.SetupRelayResponse.SerializeToString,
            ),
            'AllocateWSTunnel': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateWSTunnel,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.AllocateWSTunnelRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.AllocateWSTunnelResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.HealthCheckRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ScopeConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.ScopeConnect,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ScopeConnectRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ScopeConnectResponse.SerializeToString,
            ),
            'ScopeDisconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.ScopeDisconnect,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ScopeDisconnectRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ScopeDisconnectResponse.SerializeToString,
            ),
            'ApplyFirewall': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyFirewall,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ApplyFirewallRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ApplyFirewallResponse.SerializeToString,
            ),
            'ResetFirewall': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetFirewall,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ResetFirewallRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ResetFirewallResponse.SerializeToString,
            ),
            'GetFirewallStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFirewallStatus,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.GetFirewallStatusRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.GetFirewallStatusResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.Event.SerializeToString,
            ),
            'CreateEgressProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEgressProfile,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.CreateEgressProfileRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.EgressProfileResponse.SerializeToString,
            ),
            'UpdateEgressProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEgressProfile,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.UpdateEgressProfileRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.EgressProfileResponse.SerializeToString,
            ),
            'DeleteEgressProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEgressProfile,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteEgressProfileRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteEgressProfileResponse.SerializeToString,
            ),
            'ListEgressProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEgressProfiles,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListEgressProfilesRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListEgressProfilesResponse.SerializeToString,
            ),
            'EnableExit': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableExit,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.EnableExitRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.EnableExitResponse.SerializeToString,
            ),
            'DisableExit': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableExit,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DisableExitRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.DisableExitResponse.SerializeToString,
            ),
            'CreateIngressProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIngressProfile,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.CreateIngressProfileRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.IngressProfileResponse.SerializeToString,
            ),
            'UpdateIngressProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIngressProfile,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.UpdateIngressProfileRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.IngressProfileResponse.SerializeToString,
            ),
            'DeleteIngressProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIngressProfile,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteIngressProfileRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteIngressProfileResponse.SerializeToString,
            ),
            'ListIngressProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIngressProfiles,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListIngressProfilesRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListIngressProfilesResponse.SerializeToString,
            ),
            'CreateQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQuota,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.CreateQuotaRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.QuotaResponse.SerializeToString,
            ),
            'UpdateQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQuota,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.UpdateQuotaRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.QuotaResponse.SerializeToString,
            ),
            'DeleteQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteQuota,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteQuotaRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteQuotaResponse.SerializeToString,
            ),
            'ListQuotas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQuotas,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListQuotasRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListQuotasResponse.SerializeToString,
            ),
            'GetQuotaUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuotaUsage,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.GetQuotaUsageRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.GetQuotaUsageResponse.SerializeToString,
            ),
            'ResetQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetQuota,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ResetQuotaRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ResetQuotaResponse.SerializeToString,
            ),
            'ListPathStates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPathStates,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListPathStatesRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListPathStatesResponse.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListPoliciesRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListPoliciesResponse.SerializeToString,
            ),
            'ReloadPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadPolicies,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ReloadPoliciesRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ReloadPoliciesResponse.SerializeToString,
            ),
            'ListL7Flows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListL7Flows,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListL7FlowsRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListL7FlowsResponse.SerializeToString,
            ),
            'ListL7Totals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListL7Totals,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListL7TotalsRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListL7TotalsResponse.SerializeToString,
            ),
            'ListAnomalies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAnomalies,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListAnomaliesRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListAnomaliesResponse.SerializeToString,
            ),
            'CreateCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCircuit,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.CreateCircuitRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.CircuitResponse.SerializeToString,
            ),
            'UpdateCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCircuit,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.UpdateCircuitRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.CircuitResponse.SerializeToString,
            ),
            'DeleteCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCircuit,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteCircuitRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.DeleteCircuitResponse.SerializeToString,
            ),
            'ListCircuits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCircuits,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListCircuitsRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListCircuitsResponse.SerializeToString,
            ),
            'InitCA': grpc.unary_unary_rpc_method_handler(
                    servicer.InitCA,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.InitCARequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.InitCAResponse.SerializeToString,
            ),
            'CAStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CAStatus,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.CAStatusRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.CAStatusResponse.SerializeToString,
            ),
            'IssueCert': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueCert,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.IssueCertRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.IssueCertResponse.SerializeToString,
            ),
            'ListCerts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCerts,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ListCertsRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ListCertsResponse.SerializeToString,
            ),
            'RevokeCert': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeCert,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.RevokeCertRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.RevokeCertResponse.SerializeToString,
            ),
            'ExportTrust': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportTrust,
                    request_deserializer=gmesh_dot_v1_dot_gmesh__pb2.ExportTrustRequest.FromString,
                    response_serializer=gmesh_dot_v1_dot_gmesh__pb2.ExportTrustResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gmesh.v1.GMesh', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GMesh(object):
    """GMesh is the control-plane API exposed by the gmeshd daemon over a Unix
    socket. The GritivaCore agent, gmeshctl, and any other local process talks
    to gmeshd through this service.

    All mutating RPCs are idempotent on the {peer_id, mesh_ip} primary key.
    """

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/Join',
            gmesh_dot_v1_dot_gmesh__pb2.JoinRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.JoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Leave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/Leave',
            gmesh_dot_v1_dot_gmesh__pb2.LeaveRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.LeaveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/Status',
            gmesh_dot_v1_dot_gmesh__pb2.StatusRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/Version',
            gmesh_dot_v1_dot_gmesh__pb2.VersionRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.VersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/AddPeer',
            gmesh_dot_v1_dot_gmesh__pb2.AddPeerRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.AddPeerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemovePeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/RemovePeer',
            gmesh_dot_v1_dot_gmesh__pb2.RemovePeerRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.RemovePeerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/UpdatePeer',
            gmesh_dot_v1_dot_gmesh__pb2.UpdatePeerRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.UpdatePeerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListPeers',
            gmesh_dot_v1_dot_gmesh__pb2.ListPeersRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListPeersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPeerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/GetPeerStats',
            gmesh_dot_v1_dot_gmesh__pb2.GetPeerStatsRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.GetPeerStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DiscoverNAT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/DiscoverNAT',
            gmesh_dot_v1_dot_gmesh__pb2.DiscoverNATRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.DiscoverNATResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HolePunch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/HolePunch',
            gmesh_dot_v1_dot_gmesh__pb2.HolePunchRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.HolePunchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetupRelay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/SetupRelay',
            gmesh_dot_v1_dot_gmesh__pb2.SetupRelayRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.SetupRelayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AllocateWSTunnel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/AllocateWSTunnel',
            gmesh_dot_v1_dot_gmesh__pb2.AllocateWSTunnelRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.AllocateWSTunnelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/HealthCheck',
            gmesh_dot_v1_dot_gmesh__pb2.HealthCheckRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ScopeConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ScopeConnect',
            gmesh_dot_v1_dot_gmesh__pb2.ScopeConnectRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ScopeConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ScopeDisconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ScopeDisconnect',
            gmesh_dot_v1_dot_gmesh__pb2.ScopeDisconnectRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ScopeDisconnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyFirewall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ApplyFirewall',
            gmesh_dot_v1_dot_gmesh__pb2.ApplyFirewallRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ApplyFirewallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetFirewall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ResetFirewall',
            gmesh_dot_v1_dot_gmesh__pb2.ResetFirewallRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ResetFirewallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFirewallStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/GetFirewallStatus',
            gmesh_dot_v1_dot_gmesh__pb2.GetFirewallStatusRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.GetFirewallStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/gmesh.v1.GMesh/SubscribeEvents',
            gmesh_dot_v1_dot_gmesh__pb2.SubscribeEventsRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEgressProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/CreateEgressProfile',
            gmesh_dot_v1_dot_gmesh__pb2.CreateEgressProfileRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.EgressProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEgressProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/UpdateEgressProfile',
            gmesh_dot_v1_dot_gmesh__pb2.UpdateEgressProfileRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.EgressProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEgressProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/DeleteEgressProfile',
            gmesh_dot_v1_dot_gmesh__pb2.DeleteEgressProfileRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.DeleteEgressProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListEgressProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListEgressProfiles',
            gmesh_dot_v1_dot_gmesh__pb2.ListEgressProfilesRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListEgressProfilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableExit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/EnableExit',
            gmesh_dot_v1_dot_gmesh__pb2.EnableExitRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.EnableExitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisableExit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/DisableExit',
            gmesh_dot_v1_dot_gmesh__pb2.DisableExitRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.DisableExitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateIngressProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/CreateIngressProfile',
            gmesh_dot_v1_dot_gmesh__pb2.CreateIngressProfileRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.IngressProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateIngressProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/UpdateIngressProfile',
            gmesh_dot_v1_dot_gmesh__pb2.UpdateIngressProfileRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.IngressProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteIngressProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/DeleteIngressProfile',
            gmesh_dot_v1_dot_gmesh__pb2.DeleteIngressProfileRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.DeleteIngressProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListIngressProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListIngressProfiles',
            gmesh_dot_v1_dot_gmesh__pb2.ListIngressProfilesRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListIngressProfilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/CreateQuota',
            gmesh_dot_v1_dot_gmesh__pb2.CreateQuotaRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.QuotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/UpdateQuota',
            gmesh_dot_v1_dot_gmesh__pb2.UpdateQuotaRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.QuotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/DeleteQuota',
            gmesh_dot_v1_dot_gmesh__pb2.DeleteQuotaRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.DeleteQuotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListQuotas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListQuotas',
            gmesh_dot_v1_dot_gmesh__pb2.ListQuotasRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListQuotasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetQuotaUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/GetQuotaUsage',
            gmesh_dot_v1_dot_gmesh__pb2.GetQuotaUsageRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.GetQuotaUsageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ResetQuota',
            gmesh_dot_v1_dot_gmesh__pb2.ResetQuotaRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ResetQuotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPathStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListPathStates',
            gmesh_dot_v1_dot_gmesh__pb2.ListPathStatesRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListPathStatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListPolicies',
            gmesh_dot_v1_dot_gmesh__pb2.ListPoliciesRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListPoliciesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReloadPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ReloadPolicies',
            gmesh_dot_v1_dot_gmesh__pb2.ReloadPoliciesRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ReloadPoliciesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListL7Flows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListL7Flows',
            gmesh_dot_v1_dot_gmesh__pb2.ListL7FlowsRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListL7FlowsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListL7Totals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListL7Totals',
            gmesh_dot_v1_dot_gmesh__pb2.ListL7TotalsRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListL7TotalsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListAnomalies',
            gmesh_dot_v1_dot_gmesh__pb2.ListAnomaliesRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListAnomaliesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/CreateCircuit',
            gmesh_dot_v1_dot_gmesh__pb2.CreateCircuitRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.CircuitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/UpdateCircuit',
            gmesh_dot_v1_dot_gmesh__pb2.UpdateCircuitRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.CircuitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/DeleteCircuit',
            gmesh_dot_v1_dot_gmesh__pb2.DeleteCircuitRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.DeleteCircuitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCircuits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListCircuits',
            gmesh_dot_v1_dot_gmesh__pb2.ListCircuitsRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListCircuitsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitCA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/InitCA',
            gmesh_dot_v1_dot_gmesh__pb2.InitCARequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.InitCAResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CAStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/CAStatus',
            gmesh_dot_v1_dot_gmesh__pb2.CAStatusRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.CAStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IssueCert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/IssueCert',
            gmesh_dot_v1_dot_gmesh__pb2.IssueCertRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.IssueCertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ListCerts',
            gmesh_dot_v1_dot_gmesh__pb2.ListCertsRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ListCertsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokeCert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/RevokeCert',
            gmesh_dot_v1_dot_gmesh__pb2.RevokeCertRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.RevokeCertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExportTrust(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gmesh.v1.GMesh/ExportTrust',
            gmesh_dot_v1_dot_gmesh__pb2.ExportTrustRequest.SerializeToString,
            gmesh_dot_v1_dot_gmesh__pb2.ExportTrustResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
