#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop gmeshd.service || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
