"""End-to-end bridge tests against a live gmeshd subprocess."""

from __future__ import annotations

import asyncio
import json

import pytest

from gmesh_bridge import EventForwarder, GmeshBridge, Translator
from gmesh_bridge.translator import UnknownMessageType, known_message_types


@pytest.mark.asyncio
async def test_version_and_status(daemon):
    br = await GmeshBridge.connect(socket_path=daemon["socket"])
    try:
        v = await br.version()
        assert v["version"]
        st = await br.status()
        assert st["joined"] is False
        assert st["peer_count"] == 0
    finally:
        await br.close()


@pytest.mark.asyncio
async def test_translator_scope_roundtrip(daemon):
    br = await GmeshBridge.connect(socket_path=daemon["socket"])
    t = Translator(br)
    try:
        resp = await t.handle({
            "type": "scope_mesh_connect",
            "scope_id": 77,
            "scope_mesh_ip": "10.200.0.77",
            "veth_cidr": "10.50.77.0/30",
            "vm_veth_ip": "10.50.77.1",
            "scope_ip": "10.50.77.2",
            "listen_port": 51877,
        })
        assert resp["type"] == "scope_mesh_connected"
        assert resp["success"] is True
        assert resp["scope_id"] == 77
        assert resp["public_key"]  # generated by gmeshd

        off = await t.handle({"type": "scope_mesh_disconnect", "scope_id": 77})
        assert off["type"] == "scope_mesh_disconnected"
        assert off["success"] is True
    finally:
        await br.close()


@pytest.mark.asyncio
async def test_translator_firewall_roundtrip(daemon):
    br = await GmeshBridge.connect(socket_path=daemon["socket"])
    t = Translator(br)
    try:
        resp = await t.handle({
            "type": "mesh_firewall_apply",
            "default_policy": "accept",
            "rules": [
                {"id": 1, "name": "allow ssh", "enabled": True, "priority": 100,
                 "action": 1, "protocol": 2, "port_range": "22",
                 "direction": "inbound"},
            ],
        })
        assert resp["type"] == "mesh_firewall_applied"
        assert resp["success"] is True
        assert resp["applied_count"] == 1

        status = await t.handle({"type": "mesh_firewall_status"})
        assert status["type"] == "mesh_firewall_status"
        assert status["active_rules"] == 1

        reset = await t.handle({"type": "mesh_firewall_reset"})
        assert reset["success"] is True
    finally:
        await br.close()


@pytest.mark.asyncio
async def test_translator_unknown_type_raises(daemon):
    br = await GmeshBridge.connect(socket_path=daemon["socket"])
    t = Translator(br)
    try:
        with pytest.raises(UnknownMessageType):
            await t.handle({"type": "totally_not_a_real_mesh_message"})
    finally:
        await br.close()


@pytest.mark.asyncio
async def test_event_forwarder_translates(daemon):
    br = await GmeshBridge.connect(socket_path=daemon["socket"])
    fwd = EventForwarder(br)
    try:
        collector = asyncio.create_task(_collect_n(fwd, 2))
        await asyncio.sleep(0.1)

        # Trigger two events.
        t = Translator(br)
        await t.handle({
            "type": "scope_mesh_connect",
            "scope_id": 88, "scope_mesh_ip": "10.200.0.88",
            "veth_cidr": "10.50.88.0/30", "vm_veth_ip": "10.50.88.1",
            "scope_ip": "10.50.88.2", "listen_port": 51888,
        })
        await t.handle({"type": "scope_mesh_disconnect", "scope_id": 88})

        msgs = await asyncio.wait_for(collector, timeout=5.0)
        types = [m["type"] for m in msgs]
        assert "scope_mesh_connected" in types
        assert "scope_mesh_disconnected" in types
        # Scope-connected frame carries the mesh_ip payload.
        for m in msgs:
            if m["type"] == "scope_mesh_connected":
                assert m.get("mesh_ip") == "10.200.0.88"
    finally:
        await br.close()


async def _collect_n(fwd, n):
    out = []
    async for m in fwd.stream():
        out.append(m)
        if len(out) >= n:
            break
    return out


def test_known_message_types_has_16_entries():
    types = known_message_types()
    assert len(types) == 16
    # Quick sanity check on representative entries.
    for required in ("mesh_join", "mesh_add_peer", "scope_mesh_connect",
                     "mesh_firewall_apply"):
        assert required in types


@pytest.mark.asyncio
async def test_event_payload_is_valid_json(daemon):
    br = await GmeshBridge.connect(socket_path=daemon["socket"])
    try:
        # Trigger a firewall_applied event and verify the raw payload_json
        # parses (we use events client directly, not the translator, to
        # exercise raw pass-through).
        collector = asyncio.create_task(_collect_raw(br, 1))
        await asyncio.sleep(0.1)
        await br.apply_firewall([], default_policy="accept")
        evs = await asyncio.wait_for(collector, timeout=5.0)
        # payload_json should be empty-dict-compatible JSON.
        parsed = json.loads(evs[0]["payload_json"]) if evs[0]["payload_json"] else {}
        assert isinstance(parsed, dict)
    finally:
        await br.close()


async def _collect_raw(br, n):
    out = []
    async for ev in br.subscribe_events(["firewall_applied"]):
        out.append(ev)
        if len(out) >= n:
            break
    return out
